config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :admins
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :students
resources :instructors
resources :cohorts
resources :courses
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    has_many :students
    has_one :instructor
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = Cohort.all.order(:id)
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
    @cohorts = Cohort.find(params[:id])
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
  end

  # GET /cohorts/1/edit
  def edit
    @cohort = Cohort.find(params[:id]) 
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        format.js {puts "save cohort with js"}
        format.html { redirect_to @cohort, notice: 'Cohort was successfully created.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.error
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    @cohort = Cohort.find(params[:id])
    @cohort.update(cohort_params)

    respond_to do |format|
      if @cohort.update(cohort_params)
      
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohort }
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy

    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params.require(:cohort).permit(:name, :start_date, :end_date, :course_id)
    end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_cohort.html.erb
<tr id="cohort-<%= cohort.id%>">
     <td><%= cohort.name %></td>   
     <td><%= cohort.start_date %></td> 
     <td><%= cohort.end_date %></td>
     <td><%= cohort.course_id %></td>

     <td><%= link_to 'Show',  "/cohorts/#{cohort.id}"%></td>
     <td><%= link_to 'Edit', edit_cohort_path(cohort), remote:true %></td>
     <td><%= link_to 'Delete', cohort_path(cohort), method: :delete, remote:true, data: { confirm: 'Are you sure you want to delete this?' } %></td>
</tr> 

app/views/cohorts/_form.html.erb
<%= form_for @cohort,  remote: true do |f| %>
  <div class="field"> 
  <%= f.label :name %>:
  <%= f.text_field :name, id: :cohort_name %>
  </div>

 <div class="field"> 
  <%= f.label :start_date %>:
  <%= f.text_field :start_date, id: :cohort_start_date %>
  </div>

 <div class="field"> 
  <%= f.label :end_date %>:
  <%= f.text_field :end_date, id: :cohort_end_date %>
  </div>

 <div class="field"> 
  <%= f.label :course_id %>:
  <%= f.text_field :course_id, id: :cohort_course_id %>
  </div>

  <div class="action">
  <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/cohorts/cohort_test.html.erb
<h1> THis is my Cohort template being rendered from my create.js.erb </h1>
<%= @new_cohort.name %>

app/views/cohorts/create.js.erb
console.log('I am hitting this file for the create action')

//Hide my new task form because the user has now submitted the data
form.style.display = "none";

//Render my new cohort into a partial and render that partial onto the screen via DOM manipulation

document.getElementById('Cohorts').insertAdjacentHTML('beforeend', '<%= j render partial: "cohort", locals: {cohort: @cohort} %>');

app/views/cohorts/destroy.js.erb
console.log('Im in the destroy js file')
$('#cohort-<%= @cohort.id %>').fadeOut(300);

app/views/cohorts/edit.html.erb
<h1>Editing Cohort</h1>
<h1>New Cohort</h1>

<%= render 'form', cohort: @cohort %>

app/views/cohorts/edit.js.erb
//confirm I am in this file
console.log('I am hitting the js file for edit')

//Grab the specific place at which the cohort I want to edit exists
cohortdiv = document.getElementById('cohort-<%= @cohort.id%>')

//console log that task that I clicked on 
console.log("Current Cohort clicked " + cohortdiv.innerText)

//Gave up here and had to use JQuery to replace the TR element becuase trs dont like forms inside of them 
$(cohortdiv).replaceWith("<%= j (render 'form') %>");

app/views/cohorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cohorts</h1>

<table>
  <thead>
     <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Course ID</th>
    </tr>
  </thead>

  <tbody id="Cohorts">
    <% @cohorts.each do |cohort| %>
      
      <%= render cohort %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cohort', new_cohort_path, remote: true, id: "ajaxcall" %>
<div id='cohort_form'></div>

app/views/cohorts/index.js.erb
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });

app/views/cohorts/new.html.erb
<h1>New Cohort</h1>

<%= render 'form', cohort: @cohort %>

app/views/cohorts/new.js.erb
console.log('Im hitting this file for the new action');

//Selects hidden form element on index.html.erb
let form = document.getElementById('cohort_form');

//set the innerHTML to a string of html elements
form.innerHTML = "<%= j (render 'form') %>";

form.style.display = "block";

app/views/cohorts/show.html.erb
<p id="notice"><%= notice %></p>
 <div class="container">
<p>
<strong>Name</strong>
<%= @cohort.name %>
</p>

<p>
<strong>Start Date</strong>
<%= @cohort.start_date %>

</p>
<h2>Instructor</h2>
<p>
<%=@cohort.instructor.try(:last_name)%>
</p>
<br>
<h2>Students</h2>
<% @cohort.students.all.each do |student| %>

<p><%= student.first_name + " " +student.last_name %>
</p>
   <% end %>
<%= link_to 'Edit', edit_cohort_path(@cohort) %> |
<%= link_to 'Back', cohorts_path %>
</div>